services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"

