# Generated by Django 5.0.6 on 2024-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("-date_upload",)},
        ),
        migrations.AlterField(
            model_name="menu",
            name="date_upload",
            field=models.DateField(auto_now_add=True),
        ),
    ]
