# Generated by Django 5.0.6 on 2024-05-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menu_options_alter_menu_date_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="restaurant.restaurant",
            ),
        ),
    ]
