# Generated by Django 5.0.6 on 2024-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_menu_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="voters",
            field=models.ManyToManyField(blank=True, to="restaurant.employee"),
        ),
    ]
